//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmcErr", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.SmcError")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.McuHttpError))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.VctError))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.Tex0Error))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.Mcu8650Error))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.Mcu9660Error))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.EConfError))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.UpgradeError))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.LicenseError))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.NrsError))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcAlarm))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcAlarmOri))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcAlarmOrientation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.TP3206Error))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.DataConfError))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.CgwError))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.GkErr))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.Mcu9610Error))]
    public partial class SmcErr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint ErrNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.ErrorInfo ErrorInfoParamField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint ErrNo {
            get {
                return this.ErrNoField;
            }
            set {
                if ((this.ErrNoField.Equals(value) != true)) {
                    this.ErrNoField = value;
                    this.RaisePropertyChanged("ErrNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.ErrorInfo ErrorInfoParam {
            get {
                return this.ErrorInfoParamField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorInfoParamField, value) != true)) {
                    this.ErrorInfoParamField = value;
                    this.RaisePropertyChanged("ErrorInfoParam");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorInfo", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.SmcError")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.RangeErrorInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.RmAdapterErrorInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.EmailErrorInfo))]
    public partial class ErrorInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr[] ExternErrsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr[] MultipleErrsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.ValueDictionary[][] ParametersDictionaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr[] ExternErrs {
            get {
                return this.ExternErrsField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternErrsField, value) != true)) {
                    this.ExternErrsField = value;
                    this.RaisePropertyChanged("ExternErrs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr[] MultipleErrs {
            get {
                return this.MultipleErrsField;
            }
            set {
                if ((object.ReferenceEquals(this.MultipleErrsField, value) != true)) {
                    this.MultipleErrsField = value;
                    this.RaisePropertyChanged("MultipleErrs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.ValueDictionary[][] ParametersDictionary {
            get {
                return this.ParametersDictionaryField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersDictionaryField, value) != true)) {
                    this.ParametersDictionaryField = value;
                    this.RaisePropertyChanged("ParametersDictionary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="McuHttpError", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.SmcError")]
    [System.SerializableAttribute()]
    public partial class McuHttpError : Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VctError", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.SmcError")]
    [System.SerializableAttribute()]
    public partial class VctError : Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tex0Error", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.SmcError")]
    [System.SerializableAttribute()]
    public partial class Tex0Error : Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mcu8650Error", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.SmcError")]
    [System.SerializableAttribute()]
    public partial class Mcu8650Error : Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mcu9660Error", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.SmcError")]
    [System.SerializableAttribute()]
    public partial class Mcu9660Error : Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EConfError", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.SmcError")]
    [System.SerializableAttribute()]
    public partial class EConfError : Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpgradeError", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.SmcError")]
    [System.SerializableAttribute()]
    public partial class UpgradeError : Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LicenseError", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.SmcError")]
    [System.SerializableAttribute()]
    public partial class LicenseError : Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NrsError", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.SmcError")]
    [System.SerializableAttribute()]
    public partial class NrsError : Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmcAlarm", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.SmcError")]
    [System.SerializableAttribute()]
    public partial class SmcAlarm : Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmcAlarmOri", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.SmcError")]
    [System.SerializableAttribute()]
    public partial class SmcAlarmOri : Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmcAlarmOrientation", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.SmcError")]
    [System.SerializableAttribute()]
    public partial class SmcAlarmOrientation : Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TP3206Error", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.SmcError")]
    [System.SerializableAttribute()]
    public partial class TP3206Error : Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataConfError", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.SmcError")]
    [System.SerializableAttribute()]
    public partial class DataConfError : Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CgwError", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.SmcError")]
    [System.SerializableAttribute()]
    public partial class CgwError : Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GkErr", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.SmcError")]
    [System.SerializableAttribute()]
    public partial class GkErr : Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mcu9610Error", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.SmcError")]
    [System.SerializableAttribute()]
    public partial class Mcu9610Error : Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RangeErrorInfo", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.SmcError")]
    [System.SerializableAttribute()]
    public partial class RangeErrorInfo : Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.ErrorInfo {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RmAdapterErrorInfo", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.SmcError")]
    [System.SerializableAttribute()]
    public partial class RmAdapterErrorInfo : Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.ErrorInfo {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailErrorInfo", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.SmcError")]
    [System.SerializableAttribute()]
    public partial class EmailErrorInfo : Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.ErrorInfo {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValueDictionary", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.SmcError")]
    [System.SerializableAttribute()]
    public partial class ValueDictionary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlatformType", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.Common")]
    public enum PlatformType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MONITORPLATFORM = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ELTEPLATFORM = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagesParam", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.Common")]
    [System.SerializableAttribute()]
    public partial class PagesParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberPerPageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentPage {
            get {
                return this.CurrentPageField;
            }
            set {
                if ((this.CurrentPageField.Equals(value) != true)) {
                    this.CurrentPageField = value;
                    this.RaisePropertyChanged("CurrentPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberPerPage {
            get {
                return this.NumberPerPageField;
            }
            set {
                if ((this.NumberPerPageField.Equals(value) != true)) {
                    this.NumberPerPageField = value;
                    this.RaisePropertyChanged("NumberPerPage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlatformLicenseInfo", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.Common")]
    [System.SerializableAttribute()]
    public partial class PlatformLicenseInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEltePlatformField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMonitorPlatformField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEltePlatform {
            get {
                return this.IsEltePlatformField;
            }
            set {
                if ((this.IsEltePlatformField.Equals(value) != true)) {
                    this.IsEltePlatformField = value;
                    this.RaisePropertyChanged("IsEltePlatform");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMonitorPlatform {
            get {
                return this.IsMonitorPlatformField;
            }
            set {
                if ((this.IsMonitorPlatformField.Equals(value) != true)) {
                    this.IsMonitorPlatformField = value;
                    this.RaisePropertyChanged("IsMonitorPlatform");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Camera", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.Common")]
    [System.SerializableAttribute()]
    public partial class Camera : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMuteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsQuietField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.CameraStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceType {
            get {
                return this.DeviceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceTypeField, value) != true)) {
                    this.DeviceTypeField = value;
                    this.RaisePropertyChanged("DeviceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMute {
            get {
                return this.IsMuteField;
            }
            set {
                if ((this.IsMuteField.Equals(value) != true)) {
                    this.IsMuteField = value;
                    this.RaisePropertyChanged("IsMute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsQuiet {
            get {
                return this.IsQuietField;
            }
            set {
                if ((this.IsQuietField.Equals(value) != true)) {
                    this.IsQuietField = value;
                    this.RaisePropertyChanged("IsQuiet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string No {
            get {
                return this.NoField;
            }
            set {
                if ((object.ReferenceEquals(this.NoField, value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentID {
            get {
                return this.ParentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentIDField, value) != true)) {
                    this.ParentIDField = value;
                    this.RaisePropertyChanged("ParentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.CameraStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CameraStatus", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.Common")]
    public enum CameraStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Offline = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Online = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CameraGroup", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.Common")]
    [System.SerializableAttribute()]
    public partial class CameraGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string No {
            get {
                return this.NoField;
            }
            set {
                if ((object.ReferenceEquals(this.NoField, value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentID {
            get {
                return this.ParentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentIDField, value) != true)) {
                    this.ParentIDField = value;
                    this.RaisePropertyChanged("ParentID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NodeRelation", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.Common")]
    [System.SerializableAttribute()]
    public partial class NodeRelation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.NodeType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string No {
            get {
                return this.NoField;
            }
            set {
                if ((object.ReferenceEquals(this.NoField, value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.NodeType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NodeType", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.Common")]
    public enum NodeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NONE = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CAMERA = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GROUP = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PageInfo", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.Common")]
    [System.SerializableAttribute()]
    public partial class PageInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRecordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentPage {
            get {
                return this.CurrentPageField;
            }
            set {
                if ((this.CurrentPageField.Equals(value) != true)) {
                    this.CurrentPageField = value;
                    this.RaisePropertyChanged("CurrentPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPages {
            get {
                return this.TotalPagesField;
            }
            set {
                if ((this.TotalPagesField.Equals(value) != true)) {
                    this.TotalPagesField = value;
                    this.RaisePropertyChanged("TotalPages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecords {
            get {
                return this.TotalRecordsField;
            }
            set {
                if ((this.TotalRecordsField.Equals(value) != true)) {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PtzCommandType", Namespace="http://schemas.datacontract.org/2004/07/CgwMonitorManage.Common")]
    public enum PtzCommandType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PTZ_CMD_ZOOM_IN = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PTZ_CMD_ZOOM_OUT = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PTZ_CMD_FOCUS_IN = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PTZ_CMD_FOCUS_OUT = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PTZ_CMD_IRIS_ENLARGE = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PTZ_CMD_IRIS_SHRINK = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PTZ_CMD_UP = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PTZ_CMD_DOWN = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PTZ_CMD_LEFT = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PTZ_CMD_RIGHT = 10,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CgwMonitorManageServiceReference.IMonitorManageService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IMonitorManageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorManageService/Connect", ReplyAction="http://tempuri.org/IMonitorManageService/ConnectResponse")]
        Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr Connect(out string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorManageService/Disconnect", ReplyAction="http://tempuri.org/IMonitorManageService/DisconnectResponse")]
        Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr Disconnect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorManageService/GetAllCameras", ReplyAction="http://tempuri.org/IMonitorManageService/GetAllCamerasResponse")]
        Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr GetAllCameras(out Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.Camera[] cameraList, out Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.CameraGroup[] groupList, out Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.NodeRelation[] nodeRelationList, out Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.PageInfo pagesInfo, Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.PlatformType platformType, Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.PagesParam pageParam, Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.PlatformLicenseInfo licenseInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorManageService/RefreshMonitorCamera", ReplyAction="http://tempuri.org/IMonitorManageService/RefreshMonitorCameraResponse")]
        Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr RefreshMonitorCamera();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorManageService/GetRefreshStatus", ReplyAction="http://tempuri.org/IMonitorManageService/GetRefreshStatusResponse")]
        Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr GetRefreshStatus(out Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr refreshStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorManageService/StartReceiveVideoByPipe", ReplyAction="http://tempuri.org/IMonitorManageService/StartReceiveVideoByPipeResponse")]
        Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr StartReceiveVideoByPipe(out string pipeName, string cameraNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorManageService/StopReceiveVideoByPipe", ReplyAction="http://tempuri.org/IMonitorManageService/StopReceiveVideoByPipeResponse")]
        Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr StopReceiveVideoByPipe(string cameraNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorManageService/StartControlPtz", ReplyAction="http://tempuri.org/IMonitorManageService/StartControlPtzResponse")]
        Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr StartControlPtz(string cameraNo, Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.PtzCommandType ptzCommand, int param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorManageService/StopControlPtz", ReplyAction="http://tempuri.org/IMonitorManageService/StopControlPtzResponse")]
        Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr StopControlPtz(string cameraNo, Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.PtzCommandType ptzCommandType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorManageService/SetMic", ReplyAction="http://tempuri.org/IMonitorManageService/SetMicResponse")]
        Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr SetMic(string cameraNo, bool isOn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorManageService/SetSpeaker", ReplyAction="http://tempuri.org/IMonitorManageService/SetSpeakerResponse")]
        Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr SetSpeaker(string cameraNo, bool isOn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorManageService/MakeIFrame", ReplyAction="http://tempuri.org/IMonitorManageService/MakeIFrameResponse")]
        Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr MakeIFrame(string cameraNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorManageService/KeepAliver", ReplyAction="http://tempuri.org/IMonitorManageService/KeepAliverResponse")]
        Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr KeepAliver(string sessionID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMonitorManageServiceChannel : Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.IMonitorManageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonitorManageServiceClient : System.ServiceModel.ClientBase<Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.IMonitorManageService>, Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.IMonitorManageService {
        
        public MonitorManageServiceClient() {
        }
        
        public MonitorManageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonitorManageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorManageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorManageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr Connect(out string sessionID) {
            return base.Channel.Connect(out sessionID);
        }
        
        public Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr Disconnect() {
            return base.Channel.Disconnect();
        }
        
        public Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr GetAllCameras(out Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.Camera[] cameraList, out Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.CameraGroup[] groupList, out Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.NodeRelation[] nodeRelationList, out Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.PageInfo pagesInfo, Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.PlatformType platformType, Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.PagesParam pageParam, Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.PlatformLicenseInfo licenseInfo) {
            return base.Channel.GetAllCameras(out cameraList, out groupList, out nodeRelationList, out pagesInfo, platformType, pageParam, licenseInfo);
        }
        
        public Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr RefreshMonitorCamera() {
            return base.Channel.RefreshMonitorCamera();
        }
        
        public Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr GetRefreshStatus(out Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr refreshStatus) {
            return base.Channel.GetRefreshStatus(out refreshStatus);
        }
        
        public Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr StartReceiveVideoByPipe(out string pipeName, string cameraNo) {
            return base.Channel.StartReceiveVideoByPipe(out pipeName, cameraNo);
        }
        
        public Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr StopReceiveVideoByPipe(string cameraNo) {
            return base.Channel.StopReceiveVideoByPipe(cameraNo);
        }
        
        public Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr StartControlPtz(string cameraNo, Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.PtzCommandType ptzCommand, int param) {
            return base.Channel.StartControlPtz(cameraNo, ptzCommand, param);
        }
        
        public Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr StopControlPtz(string cameraNo, Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.PtzCommandType ptzCommandType) {
            return base.Channel.StopControlPtz(cameraNo, ptzCommandType);
        }
        
        public Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr SetMic(string cameraNo, bool isOn) {
            return base.Channel.SetMic(cameraNo, isOn);
        }
        
        public Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr SetSpeaker(string cameraNo, bool isOn) {
            return base.Channel.SetSpeaker(cameraNo, isOn);
        }
        
        public Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr MakeIFrame(string cameraNo) {
            return base.Channel.MakeIFrame(cameraNo);
        }
        
        public Cgw.MonitorManageAdapter.CgwMonitorManageServiceReference.SmcErr KeepAliver(string sessionID) {
            return base.Channel.KeepAliver(sessionID);
        }
    }
}
