
// -*- C++ -*-
// $Id: Version.h 95588 2012-03-07 08:07:23Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define ACE_MAJOR_VERSION 6
#define ACE_MINOR_VERSION 1
#define ACE_BETA_VERSION 0
#define ACE_VERSION "6.1.0"
